import type { ArchitectureJson } from '@/core/types';

// 组件类型映射（处理 LLM 可能输出的变体）
export const COMPONENT_TYPE_MAP: Record<string, ArchitectureJson['components'][number]['type']> = {
  frontend: 'frontend',
  'front-end': 'frontend',
  web: 'frontend',
  ui: 'frontend',
  backend: 'backend',
  'back-end': 'backend',
  server: 'backend',
  api: 'backend',
  database: 'database',
  db: 'database',
  'data-store': 'database',
  cache: 'cache',
  redis: 'cache',
  'cache-server': 'cache',
  queue: 'queue',
  'message-queue': 'queue',
  mq: 'queue',
  'api-gateway': 'api-gateway',
  gateway: 'api-gateway',
  'auth-service': 'auth-service',
  auth: 'auth-service',
  authentication: 'auth-service',
  storage: 'storage',
  'object-storage': 'storage',
  s3: 'storage',
  cdn: 'cdn',
  'external-api': 'external-api',
  external: 'external-api',
  thirdparty: 'external-api',
};

// 架构层映射
export const LAYER_MAP: Record<string, ArchitectureJson['components'][number]['layer']> = {
  presentation: 'presentation',
  frontend: 'presentation',
  ui: 'presentation',
  application: 'application',
  service: 'application',
  api: 'application',
  domain: 'domain',
  business: 'domain',
  core: 'domain',
  infrastructure: 'infrastructure',
  infra: 'infrastructure',
  platform: 'infrastructure',
  data: 'data',
  database: 'data',
  persistence: 'data',
};

// 连接类型映射
export const CONNECTION_TYPE_MAP: Record<string, ArchitectureJson['connections'][number]['type']> = {
  http: 'http',
  rest: 'http',
  api: 'http',
  websocket: 'websocket',
  ws: 'websocket',
  tcp: 'tcp',
  grpc: 'grpc',
  database: 'database',
  db: 'database',
  sql: 'database',
  cache: 'cache',
  redis: 'cache',
  queue: 'queue',
  mq: 'queue',
  message: 'queue',
  file: 'file',
  storage: 'file',
};